### ISSUE TITLE
On Licensed Displays, you need to change it from Licensed to Free, Restart, then Free to Licensed, Restart, before Tweets will show.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-twitter#55]
### What is the expected behavior?
Tweets will show from the Twitter Widget as long as they are showing on a Licensed Display.

### What is the actual behavior?
Even though the Display is licensed, the Twitter Widget is blank. You need to change it from Licensed to Free, Restart, then Free to Licensed, Restart, before Tweets will show. 

### What steps can be taken to replicate the problem?
1. On a Licensed Display, add the Twitter Widget. Notice the Twitter Widget may not show.
2. Change it from Licensed to Free, Restart Player, then Free to Licensed, Restart player, and now Tweets will show.

**Comment by jungeunyoon** [comment]
The fix is deployed at 100%.
---

**Problem** 
Even though the Display is licensed, the Twitter Widget is blank. You need to change it from Licensed to Free, Restart, then Free to Licensed, Restart, before Tweets will show.

**Solution** 
- When licensing is changed from Licensed to Unlicensed, Twitter Widget will continue to play through Tweets once before it stops displaying.
- When licensing is changed from Unlicensed to Licensed, Twitter Widget will pick up the change and start displaying.

**How to validate** 
1. Update Player version to `RisePlayerElectron 2018.09.10.12.32 Licensed` or later. 
2. Update Twitter Widget to latest version (remove old instance in presentation and add a new instance)
3. Toggle licensing. 
 - When licensing is changed from Licensed to Unlicensed, Twitter Widget will continue to play through Tweets once before it stops displaying.
 - When licensing is changed from Unlicensed to Licensed, Twitter Widget will pick up the change and start displaying.

**Comment by robb-price** [comment]
Verified and Closed.
