### ISSUE TITLE
Twitter Widget is missing Rise Logo

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-twitter#65]
https://www.screencast.com/t/up9w4aMap

**Comment by stulees** [comment]
@sheadarlison Do you have access to our Rise Vision Twitter account? Also, did our profile images get updated at some point? I believe they must have, because the static filler tweets that Twitter Widget uses has a specific URL for `profile_image_url` and my assumption is this file no longer exists.

**Comment by sheadarlison** [comment]
@stulees I do, and the image was updated recently, could you update the widget to use this file: https://pbs.twimg.com/profile_images/1218249445676126215/8Y-ewcXg_400x400.png

Maybe download it and then upload it to a storage repo we control so it can't be broken again. 

Thoughts?

**Comment by santiagonoguez** [comment]
@sheadarlison this is now fixed !
